So you want to send an email with a confidential attachment. Maybe you just want some privacy. It is reasonable and should be easy. Yes, modern messaging platforms exist but email is so sturdy because of its ubiquity and federated nature.

The Internet standards for email encryption are PGP and S/MIME but no one seems to use them. Properly using PGP or S/MIME requires senders and recipients to be configured to use either. Usability is pretty bad and encryption in an email is not mandatory. Adoption suffers because of these. It also does not help that everybody is using a centralized web-based email service such as Gmail. 

In an ideal world, everybody should be using S/MIME. We do not have such luxury. Maybe we can look around and try to solve the problem in other ways. I will describe alternative solutions to sending encrypted email attachments. None of these will be perfect but most of these are easier to set up than PGP or S/MIME. I hope this helps with securing your transmission of documents or safeguard your privacy.



=== Password-protected Zip files

The most widely used solution. From schools to corporate policies. This basic solution has the lowest cost and interoperability is a non-issue. Files are password protected by the sender then a password is predetermined per recipient. The password act like a pre-shared key. If dynamic passwords are required, these can be sent through another channel or out-of-band communication. Mentioning the password within the same email or even another email message defeats the purpose of protecting files.

=== Stateless web application

=== Content Collaboration Platform  (cloud or on-premises)

=== Email Security SaaS

=== Drive/Shares

=== Project Management SaaS
