== protojank

* Date: 2021-Mar-04
* Deciders: @tongson
* Status: PROPOSED

=== Context

Rust can compile to dynamic libraries for C ABI interoperability. LuaJIT's FFI is extremely good and fast. With this combination we can take advantage of the huge catalog of Rust crates. It is possible to write Rust libraries that LuaJIT can call into. We decide here the protocol to which Rust and LuaJIT can interface.

==== Decision Drivers

* Plaintext
* Simple
* Safe

==== Considered Options

===== (a) JSON
This is the default choice for plaintext protocols but it comes with sustained overhead if used all the time. The second standalone choice. We will still use JSON as part of the protocol.

===== (b) CBOR
Another good choice but CBOR modules between Rust and Lua do not cooperate well.

===== (c) Structs
The obvious choice but passing around Structs seems complicated. C and Rust Structs are not the same.

===== (d) Mixed
The solution we ended up with is a combination of C0 control codes, JSON, and base64.


=== Decision, Solution

The chosen option is named `protojank` because some people might think it's janky. We are ahead of them here. We will use a combination of ASCII C0 codes, JSON, and base64.

==== Constraints, Convention

* Only transmission and device control codes *SHALL* be used.
* Other codes like format effectors and information separators *MUST NOT* be used.
* C1 codes *MUST NOT* be used.
* Untrusted input *MUST* be encoded as base64 before adding as a JSON data value.
* C0 codes that has meaning in C *MUST NOT* be used. Example: NUL, BEL, etc.
* C0 codes that has meaning in keyboard input or Unix terminals *MUST NOT* be used. Example: ETX and EOT.

==== Allowed C0 codes

.Transmission controls
[options="header,footer",width="60%"]
|=======================
|Decimal |Abbreviation |Name |Usage
|01    |SOH     |Start of Heading |Separator
|02    |STX     |Start of Text |Any or pair with ETB
|05    |ENQ     |Enquiry |Trigger response at the receiving end which may send ACK or NAK
|06    |ACK     |Acknowledge |Success
|21    |NAK     |Negative Acknowledge |Failure or error
|23    |ETB     |End of Transmission Block |End
|=======================

.Observations
* ACK, NAK resistant to bit flips
* SOH doing a flip would terminate the CString

.Device controls
[options="header,footer",width="60%"]
|=======================
|Decimal |Abbreviation |Name |Usage
|17    |DC1 |Device Control One |On
|18    |DC2 |Device Control Two |Continue
|19    |DC3 |Device Control Three |Off
|20    |DC4 |Device Control Four |Pause
|=======================

.Observations
* Can be used for state machines
* DC1, DC3 would be susceptible to bit flips *BUT* results in a NOOP

